# Learn Posture

use machine learning to recognize robot's posture (following the example in [scikit-learn-intro.ipynb](./scikit-learn-intro.ipynb) )

## 1. Data collection

We have colleceted data before, you need to add new data if you want to add new posture.

* the dateset are in *robot_pose_data* folder
* each file contains the data belongs to this posture, e.g. the data in *Back* file are collected when robot was in "Back" posture
* the data file can be load by ```pickle```, e.g. ```pickle.load(open('Back'))```, the data is a list of feature data
* the features (e.g. each row of the data) are ['LHipYawPitch', 'LHipRoll', 'LHipPitch', 'LKneePitch', 'RHipYawPitch', 'RHipRoll', 'RHipPitch', 'RKneePitch', 'AngleX', 'AngleY'], where 'AngleX' and 'AngleY' are body angle (e.g. ```Perception.imu```) and others are joint angles.

## 2. Data preprocessing

In [1]:
%pylab inline
import pickle
from os import listdir, path
import numpy as np
from sklearn import svm, metrics

ROBOT_POSE_DATA_DIR = 'robot_pose_data'

Populating the interactive namespace from numpy and matplotlib


In [2]:
classes = listdir(ROBOT_POSE_DATA_DIR)
print classes

['Knee', 'Back', 'Right', 'Crouch', 'Sit', 'Belly', 'StandInit', 'Stand', 'HeadBack', 'Frog', 'Left']


In [3]:
def load_pose_data(i):
    '''load pose data from file'''
    data = []
    target = []
    # YOUR CODE HERE
    
    
    filename = path.join(ROBOT_POSE_DATA_DIR, classes[i])
    data = pickle.load(open(filename))
    target = [classes[i]] * len(data)
    return data, target

In [4]:
# load all the data
all_data = []
all_target = []
# YOUR CODE HERE
for i in range(len(classes)):
    (data,target) = load_pose_data(i)
    all_data.extend(data)
    all_target.extend(target)
all_data = np.asarray(all_data)
all_target = np.asarray(all_target)
print 'total number of data', len(all_data)

total number of data 222


In [5]:
# shuffule data
permutation = np.random.permutation(len(all_data))
n_training_data = int(len(all_data) * 0.7)
training_data = permutation[:n_training_data]

## 3. Learn on training data

In scikit-learn, an estimator for classification is a Python object that implements the methods fit(X, y) and predict(T). An example of an estimator is the class sklearn.svm.SVC that implements support vector classification.

In [6]:
all_train_data = []
all_train_target = []
for i in training_data:
    all_train_data.append(all_data[i])
    all_train_target.append(all_target[i])
clf = svm.SVC(gamma=0.001, C=100.)

### learning

In [7]:
# YOUR CODE HERE
clf.fit(all_data[training_data],all_target[training_data])

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0, degree=3,
  gamma=0.001, kernel='rbf', max_iter=-1, probability=False,
  random_state=None, shrinking=True, tol=0.001, verbose=False)

### predicting

In [8]:
clf.predict(all_data[-1]), all_target[-1]

(array(['Left'], 
       dtype='|S9'), 'Left')

In [9]:
def evaluate(expected, predicted):
    print("Classification report:\n%s\n" % metrics.classification_report(expected, predicted))

    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

In [10]:
expected = []
predicted = []
# YOUR CODE HERE
expected = all_target[training_data]
predicted = clf.predict(all_data[training_data])
evaluate(expected, predicted)

Classification report:
             precision    recall  f1-score   support

       Back       1.00      1.00      1.00        16
      Belly       1.00      1.00      1.00        15
     Crouch       0.96      1.00      0.98        25
       Frog       1.00      1.00      1.00         5
   HeadBack       0.00      0.00      0.00         1
       Knee       1.00      1.00      1.00         7
       Left       0.93      1.00      0.96        13
      Right       1.00      0.90      0.95        10
        Sit       1.00      1.00      1.00        17
      Stand       1.00      1.00      1.00         9
  StandInit       1.00      1.00      1.00        37

avg / total       0.98      0.99      0.98       155


Confusion matrix:
[[16  0  0  0  0  0  0  0  0  0  0]
 [ 0 15  0  0  0  0  0  0  0  0  0]
 [ 0  0 25  0  0  0  0  0  0  0  0]
 [ 0  0  0  5  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  7  0  0  0  0  0]
 [ 0  0  0  0  0  0 13  0  0  0  0]
 [ 0  0  1  0 

/home/franz/anaconda2/lib/python2.7/site-packages/sklearn/metrics/classification.py:958: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## 4. Evaluate on the test data

In [11]:
expected = []
predicted = []
# YOUR CODE HERE
test_data = permutation[n_training_data:]
expected = all_target[test_data]
predicted = clf.predict(all_data[test_data])
evaluate(expected, predicted)

Classification report:
             precision    recall  f1-score   support

       Back       1.00      1.00      1.00         7
      Belly       1.00      1.00      1.00         4
     Crouch       1.00      1.00      1.00         5
       Frog       1.00      1.00      1.00         5
   HeadBack       0.00      0.00      0.00         9
       Knee       1.00      1.00      1.00         3
       Left       0.44      1.00      0.61         7
      Right       1.00      1.00      1.00         1
        Sit       1.00      1.00      1.00         9
      Stand       1.00      1.00      1.00         2
  StandInit       1.00      1.00      1.00        15

avg / total       0.81      0.87      0.82        67


Confusion matrix:
[[ 7  0  0  0  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0  0  0  0]
 [ 0  0  5  0  0  0  0  0  0  0  0]
 [ 0  0  0  5  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  9  0  0  0  0]
 [ 0  0  0  0  0  3  0  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0  0]
 [ 0  0  0  0 

## 5. Deploy to the real system

We can simple use `pickle` module to serialize the trained classifier.

In [12]:
import pickle
ROBOT_POSE_CLF = 'robot_pose.pkl'
pickle.dump(clf, open(ROBOT_POSE_CLF, 'w'))

Then, in the application we can load the trained classifier again.

In [13]:
clf2 = pickle.load(open(ROBOT_POSE_CLF))
clf2.predict(all_data[-1]), all_target[-1]

(array(['Left'], 
       dtype='|S9'), 'Left')